Feat/171 refactor app no getinitialprops
PRX/theworld.org pull request #175
Opened 2021-05-27 18:56 UTC by rpeterman-gp

Closes #[ISSUE_ID]

- [List what the PR does...]

## To Review

- [ ] Use the Preview link located in the Now comment below.

> ...or...

- [ ] Checkout Branch.
- [ ] Run `yarn`.
- [ ] Run `yarn dev:start`.
- [ ] Go to [localhost:3000](https://localhost:3000).

> ...then...

- [ ] [Add more review steps...]

2021-06-04 02:17 UTC, brandonhundt commented
So fast! Passes my functional review. I wonder if we want to get someone else on the code review with a bit more React knowledge just to ensure that all looks good. (FYI @kookster)

2021-06-04 02:20 UTC, brandonhundt requested changes
Tag pages are returning a 500 error.

https://theworldorg-git-feat-171-refactor-app-no-getinitialpr-468d39.vercel.app/country/united-states

https://theworldorg-git-feat-171-refactor-app-no-getinitialpr-468d39.vercel.app/continent/north-america

2021-06-07 15:37 UTC, rpeterman-gp commented
@brandonhundt Term pages should now load w/o error now.

2021-06-07 15:53 UTC, brandonhundt approved these changes
Passes functional review. Would like to see if we can get a more thorough code review before merging, if possible.

2021-06-17 14:35 UTC, brandonhundt commented
@rpeterman-gp Great improvements thus far! When do you plan to call this PR complete?

2021-06-17 17:02 UTC, rpeterman-gp commented
@brandonhundt I would like to call it done. Would like to have someone else familiar with webpack to have a look at at least the `next.config.js` before I merge this.

2021-06-17 21:27 UTC, svevang approved these changes
Thanks for the top level tour @rpeterman-gp. 😎 redux and react! 

The changes from getInitialProps to the new (eg. fetchPage) make sense (and 💨 are fast on production).  My react is rusty as all getout, but overall the pattern looks good and makes sense. QA and merge seems the way to go!

2021-06-17 21:27 UTC, svevang commented on README.md
> +But what rewrites do we need? None of our content URL's adhere to any one pattern. There is one characteristic of a URL that makes things a little easier: they are _unique_ to the content they delive
This is really helpful!

2021-06-17 21:27 UTC, svevang commented on README.md
> +The `render/[...alias].tsx` page will be our whole app, appart from the homepage, which remains our `index.tsx` page. Instead of routing to another page, it will be a proxy for our content components
Really good to know, e.g for spelunking,  this is where one can start.

2021-06-17 21:27 UTC, svevang commented on pages/render/[...alias].tsx
> +const DynamicTerm = dynamic(() => import('@components/pages/Term'));
Seeing the mapping of types here 👀

2021-06-17 21:27 UTC, svevang commented on lib/fetch/category/fetchCategoryStories.ts
> +): Promise<PriApiResourceResponse> => {
👀 Part of the new api access pattern

2021-06-17 21:27 UTC, svevang commented on store/actions/fetchPageData.ts
> +    data = await fetchPage(id).then(
👀 the new fetching api

2021-06-17 21:27 UTC, svevang commented on next.config.js
> +      if (!isServer) {
Makes sense! The intent here is to split out overlapping frontend code into chunks -- eliminate dupe code!

2021-06-17 21:27 UTC, svevang commented on next.config.js
> +      if (!isServer) {
Wild that this is `!isServer`, reminds me of meteor.js (back in the day!) ... code that runs on server and client (!!)

2021-06-21 16:10 UTC, merged