#228 robots.txt, ads.txt, opensearch.xml
PRX/theworld.org pull request #229
Opened 2021-10-18 21:06 UTC by brandonhundt

Closes #228 

- Adds robots.txt file pointing to an external sitemap with other suggested default settings, letting search engines know this domain is open for business.
- Creates ads.txt file, with the recommended line of code for bots to know we are not open for business. [See Page 7 of this IAB PDF](https://iabtechlab.com/wp-content/uploads/2021/03/ads.txt-1.0.3.pdf)
- updates opensearch.xml file

## To Review

- [ ] Code Review

2021-10-20 21:42 UTC, brandonhundt commented on public/opensearch.xml
> +  <Url method="get" type="text/html" template="http://admin.theworld.org/search/node/{searchTerms}" />
Would this be correct, @rpeterman-gp ?

2021-10-20 21:42 UTC, brandonhundt commented on public/opensearch.xml
> +  <Url method="get" type="text/html" template="http://admin.theworld.org/search/node/{searchTerms}" />
Or is there a frontend version?

2021-10-26 19:00 UTC, rpeterman-gp requested changes
See comments for all changes. Please revert changes to `opensearch.xml`. I'll update that file with the search page creation work.

2021-10-26 19:00 UTC, rpeterman-gp commented on public/robots.txt
> +Sitemap: https://admin.theworld.org/sitemap.xml
this should be to `sitemap.theworld.org` domain.

2021-10-26 19:00 UTC, rpeterman-gp commented on public/opensearch.xml
> +  <Url method="get" type="text/html" template="http://admin.theworld.org/search/node/{searchTerms}" />
We should use a frontend URL. I'll have to setup something. The URL will probably be `https://theworld.org/search/{searchTerms}`.

2021-10-26 19:00 UTC, rpeterman-gp commented on public/opensearch.xml
> +  <Url method="get" type="text/html" template="http://admin.theworld.org/search/node/{searchTerms}" />
Actually, I should do this change in the work that creates the search page. Can you just revert this file for now?

2021-10-28 19:27 UTC, rpeterman-gp approved these changes
:shipit:

2021-10-28 19:30 UTC, merged