Sticky donate link button
PRX/theworld.org pull request #485
Opened 2024-10-07 20:06 UTC by rpeterman-gp

- Makes donation link in header nav "sticky" to page in browsers that support CSS `animation-timeline`.

## To Review

- [ ] Use the Preview link located in the Now comment below.

> ...or...

- [ ] Checkout Branch.
- [ ] Run `yarn`.
- [ ] Run `yarn dev`.
- [ ] In Chromium browser, go to [localhost:3000](https://localhost:3000).

> ...then...

- [ ] Scroll the page and ensure donate button becomes fixed to top of page shortly after it scrolls out of view.
- [ ] Open in Firefox and Safari. Donate button should not become sticky. They do not support css `animation-timeline` yet.

2024-10-08 15:56 UTC, brandonhundt commented
@rpeterman-gp I like it on desktop, not so much for mobile. I think it lacks too much context for mobile to have a random heart floating. 

Idea... Should we stick the button to the lower right (Like a Fob)? And keep the word "donate" for the mobile button?

2024-10-09 16:15 UTC, brandonhundt requested changes
See previous comment. Thanks Rick.

2025-01-15 20:06 UTC, rpeterman-gp commented
Issue with the fab idea is we already have a fab on stories for social sharing links. It would not be a simple styling change to reposition as a fab and not have it collide with social sharing fab.

2025-01-15 20:27 UTC, brandonhundt commented
I think this is something to think about with the redesign.

On Wed, Jan 15, 2025 at 2:06 PM Rick Peterman ***@***.***>
wrote:

> Issue with the fab idea is we already have a fab on stories for social
> sharing links. It would not be a simple styling change to reposition as a
> fab and not have it collide with social sharing fab.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/PRX/theworld.org/pull/485#issuecomment-2593832385>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAC2ISZSGE7TYGW6PFSFBQT2K25VRAVCNFSM6AAAAABPQV647KVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKOJTHAZTEMZYGU>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2025-01-16 18:32 UTC, rpeterman-gp commented
Do we want to close this PR if we no longer want this feature in the current site?

2025-01-16 18:33 UTC, brandonhundt commented
We can close. Thanks

2025-01-16 18:48 UTC, rpeterman-gp commented
Closing this PR in favor of waiting for redesign to implement this feature (if it make sense in the new UI).

2025-01-16 18:48 UTC, closed without merging